version: '3'

services:
  web:
    image: php:8-apache
    container_name: php_web_inl3
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8081:80"
    stdin_open: true
    tty: true
    networks:
      - default
